//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynVis.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynVis.Data.Properties.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Угол A-B-C.
        /// </summary>
        internal static string AngleABC {
            get {
                return ResourceManager.GetString("AngleABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Массив аппликат.
        /// </summary>
        internal static string ApplicateArray {
            get {
                return ResourceManager.GetString("ApplicateArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран атом.
        /// </summary>
        internal static string AtomNotSelected {
            get {
                return ResourceManager.GetString("AtomNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атомы не могут повторятся.
        /// </summary>
        internal static string AtomsCouldNotBeRepeated {
            get {
                return ResourceManager.GetString("AtomsCouldNotBeRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет поверхности методом ЛЭПС.
        /// </summary>
        internal static string CalcLEPS {
            get {
                return ResourceManager.GetString("CalcLEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координата №{0} не больше предыдущей..
        /// </summary>
        internal static string CoordNotMore {
            get {
                return ResourceManager.GetString("CoordNotMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построение поверхности по матрице аппликат.
        /// </summary>
        internal static string CreateSurfaceByApplicateMatrix {
            get {
                return ResourceManager.GetString("CreateSurfaceByApplicateMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры динамики реакции.
        /// </summary>
        internal static string DynamicParams {
            get {
                return ResourceManager.GetString("DynamicParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element array not found or elements count less then 3..
        /// </summary>
        internal static string ElementArrayNotFoundOrElementsCountLessThen3 {
            get {
                return ResourceManager.GetString("ElementArrayNotFoundOrElementsCountLessThen3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка во введеных данных.
        /// </summary>
        internal static string ErrorInInputData {
            get {
                return ResourceManager.GetString("ErrorInInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нахождение стационарных точек на ППЭ.
        /// </summary>
        internal static string FindStationaryPoint {
            get {
                return ResourceManager.GetString("FindStationaryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry structures not found or it&apos;s count is wrong..
        /// </summary>
        internal static string GeometryStructuresNotFoundOrItsCountIsWrong {
            get {
                return ResourceManager.GetString("GeometryStructuresNotFoundOrItsCountIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сетка значений.
        /// </summary>
        internal static string GridValue {
            get {
                return ResourceManager.GetString("GridValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние B-C.
        /// </summary>
        internal static string LengthBC {
            get {
                return ResourceManager.GetString("LengthBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛЭПС.
        /// </summary>
        internal static string LEPS {
            get {
                return ResourceManager.GetString("LEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры поверхности ЛЭПС.
        /// </summary>
        internal static string LEPSParams {
            get {
                return ResourceManager.GetString("LEPSParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь реакции минимальной энергии.
        /// </summary>
        internal static string MinimalEnergyPath {
            get {
                return ResourceManager.GetString("MinimalEnergyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет пути миимальной энергии.
        /// </summary>
        internal static string MinimalEnergyPathCalculation {
            get {
                return ResourceManager.GetString("MinimalEnergyPathCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        internal static string NumberSymbol {
            get {
                return ResourceManager.GetString("NumberSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ППЭ не определена..
        /// </summary>
        internal static string PESNotSpecified {
            get {
                return ResourceManager.GetString("PESNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1.
        /// </summary>
        internal static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2.
        /// </summary>
        internal static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Динамика реакции.
        /// </summary>
        internal static string ReactionDynamic {
            get {
                return ResourceManager.GetString("ReactionDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет динамики реакции.
        /// </summary>
        internal static string ReactionDynamicCalculation {
            get {
                return ResourceManager.GetString("ReactionDynamicCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема при чтении массива энергий..
        /// </summary>
        internal static string ReadErrorEnergyArray {
            get {
                return ResourceManager.GetString("ReadErrorEnergyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемы при чтении свойств первой координаты.
        /// </summary>
        internal static string ReadErrorQ1Axes {
            get {
                return ResourceManager.GetString("ReadErrorQ1Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемы при чтении узлов первой координаты.
        /// </summary>
        internal static string ReadErrorQ1Knots {
            get {
                return ResourceManager.GetString("ReadErrorQ1Knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемы при чтении свойств второй координаты.
        /// </summary>
        internal static string ReadErrorQ2Axes {
            get {
                return ResourceManager.GetString("ReadErrorQ2Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемы при чтении узлов второй координаты.
        /// </summary>
        internal static string ReadErrorQ2Knots {
            get {
                return ResourceManager.GetString("ReadErrorQ2Knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сруктура реагирующей системы.
        /// </summary>
        internal static string ReagentSystemStructure {
            get {
                return ResourceManager.GetString("ReagentSystemStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканирование поверхности.
        /// </summary>
        internal static string ScanSurface {
            get {
                return ResourceManager.GetString("ScanSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стационарные точки.
        /// </summary>
        internal static string StationaryPoints {
            get {
                return ResourceManager.GetString("StationaryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обработать прочтенные данные..
        /// </summary>
        internal static string UbposibleSetReadData {
            get {
                return ResourceManager.GetString("UbposibleSetReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
