//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynVis.Draw.Geomtery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynVis.Draw.Geomtery.Properties.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Структура.
        /// </summary>
        internal static string SructureSection {
            get {
                return ResourceManager.GetString("SructureSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка отображения структуры.
        /// </summary>
        internal static string StructurePropertiesCustomization {
            get {
                return ResourceManager.GetString("StructurePropertiesCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координаты: {0}.
        /// </summary>
        internal static string ViewCoordinate {
            get {
                return ResourceManager.GetString("ViewCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диэдральный угол: {0:F9}.
        /// </summary>
        internal static string ViewDihedralAngel {
            get {
                return ResourceManager.GetString("ViewDihedralAngel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Растояние: {0:F9}.
        /// </summary>
        internal static string ViewDistance {
            get {
                return ResourceManager.GetString("ViewDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валентный угол: {0:F9}.
        /// </summary>
        internal static string ViewValentAngle {
            get {
                return ResourceManager.GetString("ViewValentAngle", resourceCulture);
            }
        }
    }
}
