//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynVis.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynVis.Core.Properties.LangGeneral", typeof(LangGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительно.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матрица аппликат.
        /// </summary>
        internal static string ApplicateMatrix {
            get {
                return ResourceManager.GetString("ApplicateMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступная версия: .
        /// </summary>
        internal static string AvailableVersion {
            get {
                return ResourceManager.GetString("AvailableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет об ошибке программы .
        /// </summary>
        internal static string BugReport {
            get {
                return ResourceManager.GetString("BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта для ответа: .
        /// </summary>
        internal static string CallbackEmail {
            get {
                return ResourceManager.GetString("CallbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно установить соединение с сервером..
        /// </summary>
        internal static string CanNotConnect {
            get {
                return ResourceManager.GetString("CanNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл координат.
        /// </summary>
        internal static string CoordFile {
            get {
                return ResourceManager.GetString("CoordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координата.
        /// </summary>
        internal static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание геометрии реагируюзей системы без ППЭ невозможно..
        /// </summary>
        internal static string CreatingGeometryWithoutPESUnpossible {
            get {
                return ResourceManager.GetString("CreatingGeometryWithoutPESUnpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая версия: .
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы используете самую свежую версию программы..
        /// </summary>
        internal static string CurrentVersionIsUpToDate {
            get {
                return ResourceManager.GetString("CurrentVersionIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка параметров.
        /// </summary>
        internal static string CustomizationPproperties {
            get {
                return ResourceManager.GetString("CustomizationPproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynVis Bug Report.
        /// </summary>
        internal static string DynVisBugReport {
            get {
                return ResourceManager.GetString("DynVisBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв о программе DynVis.
        /// </summary>
        internal static string DynVisResponse {
            get {
                return ResourceManager.GetString("DynVisResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение об ошибке.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение об исключении:.
        /// </summary>
        internal static string ExceptionText {
            get {
                return ResourceManager.GetString("ExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание файла.
        /// </summary>
        internal static string FileCreating {
            get {
                return ResourceManager.GetString("FileCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт не поддерживается.
        /// </summary>
        internal static string FontIsWrong {
            get {
                return ResourceManager.GetString("FontIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создана геомтерия реагируюзей системы..
        /// </summary>
        internal static string GeometryCreated {
            get {
                return ResourceManager.GetString("GeometryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неверный адресс эдектронной почты.
        /// </summary>
        internal static string InputWrongEmail {
            get {
                return ResourceManager.GetString("InputWrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масса: {0} a.е.м..
        /// </summary>
        internal static string MassOf {
            get {
                return ResourceManager.GetString("MassOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка максимума.
        /// </summary>
        internal static string MaximumPoint {
            get {
                return ResourceManager.GetString("MaximumPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить сообщение.
        /// </summary>
        internal static string MessageDoesNotSend {
            get {
                return ResourceManager.GetString("MessageDoesNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение отправлено.
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка минимума.
        /// </summary>
        internal static string MinimumPoint {
            get {
                return ResourceManager.GetString("MinimumPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна новая версия..
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует информация для сохранания..
        /// </summary>
        internal static string NothingToSave {
            get {
                return ResourceManager.GetString("NothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введено число!.
        /// </summary>
        internal static string NumberInputWrong {
            get {
                return ResourceManager.GetString("NumberInputWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}Номер: {2}{0}Масса: {3}.
        /// </summary>
        internal static string NumberOf {
            get {
                return ResourceManager.GetString("NumberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        internal static string NumberSymbol {
            get {
                return ResourceManager.GetString("NumberSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        internal static string PathNamberColumnCaption {
            get {
                return ResourceManager.GetString("PathNamberColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь реакции.
        /// </summary>
        internal static string PathNameColumnCaption {
            get {
                return ResourceManager.GetString("PathNameColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создана ППЭ..
        /// </summary>
        internal static string PesCreated {
            get {
                return ResourceManager.GetString("PesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдены точки на ППЭ..
        /// </summary>
        internal static string PESPointsFounded {
            get {
                return ResourceManager.GetString("PESPointsFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка.
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог программы.
        /// </summary>
        internal static string ProgrammLog {
            get {
                return ResourceManager.GetString("ProgrammLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1.
        /// </summary>
        internal static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2.
        /// </summary>
        internal static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан путь реакции..
        /// </summary>
        internal static string ReactionPathCreated {
            get {
                return ResourceManager.GetString("ReactionPathCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список путей реакции.
        /// </summary>
        internal static string ReactionPathList {
            get {
                return ResourceManager.GetString("ReactionPathList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пути реакции.
        /// </summary>
        internal static string ReactionPaths {
            get {
                return ResourceManager.GetString("ReactionPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранные пути?.
        /// </summary>
        internal static string RemoveSelectedPaths {
            get {
                return ResourceManager.GetString("RemoveSelectedPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Седловая точка.
        /// </summary>
        internal static string SaddlePoint {
            get {
                return ResourceManager.GetString("SaddlePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение объекта.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка сообщения.
        /// </summary>
        internal static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стационараня точка.
        /// </summary>
        internal static string StationaryPoint {
            get {
                return ResourceManager.GetString("StationaryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точки поверхности.
        /// </summary>
        internal static string SurfacePoints {
            get {
                return ResourceManager.GetString("SurfacePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точки неизвестного типа.
        /// </summary>
        internal static string UnknowTypePoint {
            get {
                return ResourceManager.GetString("UnknowTypePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий пользователя: .
        /// </summary>
        internal static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронный адресс пользователя: .
        /// </summary>
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены неверные значения.
        /// </summary>
        internal static string ValueInputWrong {
            get {
                return ResourceManager.GetString("ValueInputWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
