//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynVis.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangDimension {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangDimension() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynVis.Core.Properties.LangDimension", typeof(LangDimension).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Угол.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Градус.
        /// </summary>
        internal static string Angle_Degree {
            get {
                return ResourceManager.GetString("Angle_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}град.
        /// </summary>
        internal static string Angle_Degree_s {
            get {
                return ResourceManager.GetString("Angle_Degree_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Радиан.
        /// </summary>
        internal static string Angle_Radian {
            get {
                return ResourceManager.GetString("Angle_Radian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}рад.
        /// </summary>
        internal static string Angle_Radian_s {
            get {
                return ResourceManager.GetString("Angle_Radian_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length allowed dimensions array can not be null.
        /// </summary>
        internal static string ArrayLengthCanntBeNull {
            get {
                return ResourceManager.GetString("ArrayLengthCanntBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атто.
        /// </summary>
        internal static string Atto {
            get {
                return ResourceManager.GetString("Atto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а.
        /// </summary>
        internal static string Atto_s {
            get {
                return ResourceManager.GetString("Atto_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дека.
        /// </summary>
        internal static string Deca {
            get {
                return ResourceManager.GetString("Deca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to да.
        /// </summary>
        internal static string Deca_s {
            get {
                return ResourceManager.GetString("Deca_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деци.
        /// </summary>
        internal static string Deci {
            get {
                return ResourceManager.GetString("Deci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to д.
        /// </summary>
        internal static string Deci_s {
            get {
                return ResourceManager.GetString("Deci_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безразмерная величина.
        /// </summary>
        internal static string Dimensionless {
            get {
                return ResourceManager.GetString("Dimensionless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Dimensionless_s {
            get {
                return ResourceManager.GetString("Dimensionless_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Калория.
        /// </summary>
        internal static string Energy_Calorie {
            get {
                return ResourceManager.GetString("Energy_Calorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}кал.
        /// </summary>
        internal static string Energy_Calorie_s {
            get {
                return ResourceManager.GetString("Energy_Calorie_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Х.
        /// </summary>
        internal static string Energy_Haretree_s {
            get {
                return ResourceManager.GetString("Energy_Haretree_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Хартри.
        /// </summary>
        internal static string Energy_Hartree {
            get {
                return ResourceManager.GetString("Energy_Hartree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Джоуль.
        /// </summary>
        internal static string Energy_Joule {
            get {
                return ResourceManager.GetString("Energy_Joule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Дж.
        /// </summary>
        internal static string Energy_Joule_s {
            get {
                return ResourceManager.GetString("Energy_Joule_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экса.
        /// </summary>
        internal static string Exsa {
            get {
                return ResourceManager.GetString("Exsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Э.
        /// </summary>
        internal static string Exsa_s {
            get {
                return ResourceManager.GetString("Exsa_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фемто.
        /// </summary>
        internal static string Femto {
            get {
                return ResourceManager.GetString("Femto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ф.
        /// </summary>
        internal static string Femto_s {
            get {
                return ResourceManager.GetString("Femto_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сила.
        /// </summary>
        internal static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Дина.
        /// </summary>
        internal static string Force_Dinah {
            get {
                return ResourceManager.GetString("Force_Dinah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Дин.
        /// </summary>
        internal static string Force_Dinah_s {
            get {
                return ResourceManager.GetString("Force_Dinah_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Ньютон.
        /// </summary>
        internal static string Force_Newton {
            get {
                return ResourceManager.GetString("Force_Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Н.
        /// </summary>
        internal static string Force_Newton_s {
            get {
                return ResourceManager.GetString("Force_Newton_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гига.
        /// </summary>
        internal static string Giga {
            get {
                return ResourceManager.GetString("Giga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Г.
        /// </summary>
        internal static string Giga_s {
            get {
                return ResourceManager.GetString("Giga_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гекто.
        /// </summary>
        internal static string Hecto {
            get {
                return ResourceManager.GetString("Hecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г.
        /// </summary>
        internal static string Hecto_s {
            get {
                return ResourceManager.GetString("Hecto_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Йокто.
        /// </summary>
        internal static string Iokto {
            get {
                return ResourceManager.GetString("Iokto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to й.
        /// </summary>
        internal static string Iokto_s {
            get {
                return ResourceManager.GetString("Iokto_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Йотта.
        /// </summary>
        internal static string Iotta {
            get {
                return ResourceManager.GetString("Iotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И.
        /// </summary>
        internal static string Iotta_s {
            get {
                return ResourceManager.GetString("Iotta_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кило.
        /// </summary>
        internal static string Kilo {
            get {
                return ResourceManager.GetString("Kilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to к.
        /// </summary>
        internal static string Kilo_s {
            get {
                return ResourceManager.GetString("Kilo_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Ангстрем.
        /// </summary>
        internal static string Length_Angstrom {
            get {
                return ResourceManager.GetString("Length_Angstrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Å.
        /// </summary>
        internal static string Length_Angstrom_s {
            get {
                return ResourceManager.GetString("Length_Angstrom_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Бор.
        /// </summary>
        internal static string Length_Bohr {
            get {
                return ResourceManager.GetString("Length_Bohr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Бор.
        /// </summary>
        internal static string Length_Bohr_s {
            get {
                return ResourceManager.GetString("Length_Bohr_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Метр.
        /// </summary>
        internal static string Length_Metr {
            get {
                return ResourceManager.GetString("Length_Metr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}м.
        /// </summary>
        internal static string Length_Metr_s {
            get {
                return ResourceManager.GetString("Length_Metr_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масса.
        /// </summary>
        internal static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Дальто́н.
        /// </summary>
        internal static string Mass_Dalton {
            get {
                return ResourceManager.GetString("Mass_Dalton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}а.е.м.
        /// </summary>
        internal static string Mass_Dalton_s {
            get {
                return ResourceManager.GetString("Mass_Dalton_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Грам.
        /// </summary>
        internal static string Mass_Gram {
            get {
                return ResourceManager.GetString("Mass_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}г.
        /// </summary>
        internal static string Mass_Gram_s {
            get {
                return ResourceManager.GetString("Mass_Gram_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мега.
        /// </summary>
        internal static string Mega {
            get {
                return ResourceManager.GetString("Mega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to М.
        /// </summary>
        internal static string Mega_s {
            get {
                return ResourceManager.GetString("Mega_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Микро.
        /// </summary>
        internal static string Micro {
            get {
                return ResourceManager.GetString("Micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мк.
        /// </summary>
        internal static string Micro_s {
            get {
                return ResourceManager.GetString("Micro_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.
        /// </summary>
        internal static string Mili_s {
            get {
                return ResourceManager.GetString("Mili_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Милли.
        /// </summary>
        internal static string Milli {
            get {
                return ResourceManager.GetString("Milli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нано.
        /// </summary>
        internal static string Nano {
            get {
                return ResourceManager.GetString("Nano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to н.
        /// </summary>
        internal static string Nano_s {
            get {
                return ResourceManager.GetString("Nano_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пета.
        /// </summary>
        internal static string Peta {
            get {
                return ResourceManager.GetString("Peta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П.
        /// </summary>
        internal static string Peta_s {
            get {
                return ResourceManager.GetString("Peta_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пико.
        /// </summary>
        internal static string Pico {
            get {
                return ResourceManager.GetString("Pico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to п.
        /// </summary>
        internal static string Pico_s {
            get {
                return ResourceManager.GetString("Pico_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная длина.
        /// </summary>
        internal static string ReciprocalLength {
            get {
                return ResourceManager.GetString("ReciprocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратный {0}Ангстрем.
        /// </summary>
        internal static string ReciprocalLength_Angstrom {
            get {
                return ResourceManager.GetString("ReciprocalLength_Angstrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/{0}Å.
        /// </summary>
        internal static string ReciprocalLength_Angstrom_s {
            get {
                return ResourceManager.GetString("ReciprocalLength_Angstrom_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратный {0}Бор.
        /// </summary>
        internal static string ReciprocalLength_Bohr {
            get {
                return ResourceManager.GetString("ReciprocalLength_Bohr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/{0}Бор.
        /// </summary>
        internal static string ReciprocalLength_Bohr_s {
            get {
                return ResourceManager.GetString("ReciprocalLength_Bohr_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратный {0}метр.
        /// </summary>
        internal static string ReciprocalLength_Metr {
            get {
                return ResourceManager.GetString("ReciprocalLength_Metr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/{0}м.
        /// </summary>
        internal static string ReciprocalLength_Metr_s {
            get {
                return ResourceManager.GetString("ReciprocalLength_Metr_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санти.
        /// </summary>
        internal static string Santi {
            get {
                return ResourceManager.GetString("Santi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с.
        /// </summary>
        internal static string Santi_s {
            get {
                return ResourceManager.GetString("Santi_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тера.
        /// </summary>
        internal static string Tera {
            get {
                return ResourceManager.GetString("Tera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Секунда.
        /// </summary>
        internal static string Time_Second {
            get {
                return ResourceManager.GetString("Time_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}с.
        /// </summary>
        internal static string Time_Second_s {
            get {
                return ResourceManager.GetString("Time_Second_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зепто.
        /// </summary>
        internal static string Zepto {
            get {
                return ResourceManager.GetString("Zepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to з.
        /// </summary>
        internal static string Zepto_s {
            get {
                return ResourceManager.GetString("Zepto_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зетта.
        /// </summary>
        internal static string Zetta {
            get {
                return ResourceManager.GetString("Zetta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З.
        /// </summary>
        internal static string Zetta_s {
            get {
                return ResourceManager.GetString("Zetta_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        internal static string Тera_s {
            get {
                return ResourceManager.GetString("Тera_s", resourceCulture);
            }
        }
    }
}
